function reportPath = mbd_export_block_library_catalog(outputDir, searchDepth, includeParamValues, libraryRoots)
%MBD_EXPORT_BLOCK_LIBRARY_CATALOG Export installed Simulink library block sample.
% Description:
%   Writes a Markdown catalog of blocks found under the given library roots
%   at the requested search depth, including block type, mask type, and
%   dialog parameter names. Optionally includes each parameter's current
%   (library-default) value, which is slower and produces a larger file.
%
%   This reads the user's actual installed MATLAB/Simulink, so it reflects
%   the real release and licensed toolboxes -- it is not a hand-written or
%   memorized list.
%
% Inputs:
%   outputDir          - Optional output directory. Defaults to .MBD_agent/reports.
%   searchDepth        - Optional find_system search depth. Defaults to 4.
%   includeParamValues - Optional logical. Defaults to false. When true, adds a
%                        "name=value" pair per parameter instead of just names.
%                        Slower and produces a much larger file.
%   libraryRoots       - Optional cell array of library root names to search.
%                        Defaults to {'simulink'}, which is always present.
%                        Add toolbox-specific roots as needed, for example
%                        'sflib' for the Stateflow block library, once you
%                        know they are installed (check Simulink Library
%                        Browser or `mbd_discover_environment` apps table).
%
% Outputs:
%   reportPath         - Path to generated Markdown catalog.

if nargin < 1 || isempty(outputDir)
    outputDir = fullfile(pwd, '.MBD_agent', 'reports');
end
if nargin < 2 || isempty(searchDepth)
    searchDepth = 4;
end
if nargin < 3 || isempty(includeParamValues)
    includeParamValues = false;
end
if nargin < 4 || isempty(libraryRoots)
    libraryRoots = {'simulink'};
end
if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end
reportPath = fullfile(outputDir, 'simulink_block_library_catalog.md');
fid = fopen(reportPath, 'w');
if fid < 0
    error('mbd_export_block_library_catalog:FileOpenFailed', 'Could not write %s.', reportPath);
end
cleanupObj = onCleanup(@() fclose(fid));

fprintf(fid, '# Simulink block library catalog\n\n');
fprintf(fid, '- Generated: %s\n', datestr(now, 31));
fprintf(fid, '- MATLAB version: %s\n', version);
fprintf(fid, '- Search depth: %d\n', searchDepth);
fprintf(fid, '- Library roots: %s\n', strjoin(libraryRoots, ', '));
fprintf(fid, '- Includes parameter values: %s\n\n', tf2str(includeParamValues));
fprintf(fid, ['This file was generated by running this MATLAB session''s actual installed ' ...
    'libraries. Regenerate it after installing/removing toolboxes, or after a release ' ...
    'upgrade, since block sets and defaults change between releases.\n\n']);

totalBlocks = 0;
for r = 1:numel(libraryRoots)
    root = libraryRoots{r};
    fprintf(fid, '## Library root: `%s`\n\n', esc(root));
    try
        load_system(root);
        blocks = find_system(root, 'SearchDepth', searchDepth, 'Type', 'Block');
    catch ME
        fprintf(fid, 'Could not load/search this library root: `%s`\n\n', esc(ME.message));
        continue;
    end
    totalBlocks = totalBlocks + numel(blocks);

    if includeParamValues
        fprintf(fid, '| Library path | BlockType | MaskType | Parameters (name=value) |\n');
    else
        fprintf(fid, '| Library path | BlockType | MaskType | Parameter names |\n');
    end
    fprintf(fid, '|---|---|---|---|\n');
    for i = 1:numel(blocks)
        b = blocks{i};
        paramsText = blockParamsText(b, includeParamValues);
        fprintf(fid, '| `%s` | %s | %s | %s |\n', esc(b), esc(getp(b, 'BlockType')), esc(getp(b, 'MaskType')), esc(paramsText));
    end
    fprintf(fid, '\n');
end

fprintf(fid, '## Summary\n\n');
fprintf(fid, '- Total blocks catalogued: %d\n', totalBlocks);
rootsListText = strjoin(libraryRoots, ', ');
fprintf(fid, ['- This catalog is best-effort: not every product registers a block library ' ...
    'discoverable from %s. Cross-check the Simulink Library Browser for full coverage ' ...
    'of any toolbox you license.\n'], rootsListText);
end

function txt = blockParamsText(blockPath, includeValues)
txt = '';
try
    params = get_param(blockPath, 'DialogParameters');
    names = fieldnames(params);
catch
    return;
end
if isempty(names)
    return;
end
if ~includeValues
    txt = strjoin(names', ', ');
    return;
end
pairs = cell(1, numel(names));
for i = 1:numel(names)
    val = getp(blockPath, names{i});
    pairs{i} = sprintf('%s=%s', names{i}, val2txt(val));
end
txt = strjoin(pairs, '; ');
end

function value = getp(pathName, paramName)
try
    raw = get_param(pathName, paramName);
    value = val2txt(raw);
catch
    value = '';
end
end

function out = val2txt(value)
if isnumeric(value) || islogical(value)
    out = mat2str(value);
elseif ischar(value)
    out = value;
elseif isstring(value)
    out = char(value);
elseif iscell(value)
    out = ['cell(' num2str(numel(value)) ')'];
elseif isstruct(value)
    out = ['struct(' strjoin(fieldnames(value)', ',') ')'];
else
    try, out = char(string(value)); catch, out = ['<' class(value) '>']; end
end
out = strrep(out, newline, ' ');
end

function s = tf2str(v)
if v, s = 'true'; else, s = 'false'; end
end

function out = esc(in)
out = char(string(in));
out = strrep(out, '|', '\|');
out = strrep(out, newline, ' ');
end
